name: CI/CD

on:
  push:
    branches: 
      - main 

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2

      - name: Python version setup

        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: setup virtual env
        run: pip3 install virtualenv

      - name:  set path for env
        uses: actions/cache@v2
        id: cache-venv 
        with:
          path: venv 
          key: ${{ runner.os }}-venv-${{ hashFiles('*/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate Venv
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run in virtual env    
        run: . venv/bin/activate 

      - name: Create zip file
        run: |
          ls -la
          cd ./venv/lib/python3.9/site-packages
          zip -r9 ../../../../api.zip .
      - name: Add API files to Zip file
        run: cd ./api && zip -g ../api.zip -r .

      - name: Upload zip file 
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  Deployment:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download Lambda app
        uses: actions/download-artifact@v2
        with:
          name: api
      - name: Upload to S3
        run: aws s3 cp api.zip s3://ella-fast-api-app/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy new Lambda function
        run: aws lambda update-function-code --function-name ella-fastapi-app --s3-bucket ella-fast-api-app --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
